### ISSUE TITLE
Prefixing tests with `compat-`

### ISSUE THREAD

**Issue by phikal** [emacs-compat/compat#20]
Currently the tests have no common prefix or suffix, when using <kbd>M-x ert</kbd> you cannot just select those related to Compat.  Is there any reason no to have all the tests begin with `compat-` or anything else like that?

**Comment by minad** [comment]
No particular reason except that the tests are usually not Compat-specific. One could even import many of the Compat tests into the Emacs test suite itself, in case they are missing upstream.

**Comment by minad** [comment]
On 3/17/23 15:46, Philip wrote:
> (especially when a function is provided conditionally).

I forgot to answer to that point - if a function is provided
conditionally (and must be called via compat-call), we can call the
function explicitly via compat-call in the test suite. Furthermore we
can also call the function without compat-call, as long as we only use
the old calling convention. Since we run the test suite on all supported
Emacs versions, we will make sure that all test cases are executed
correctly.

Note that all that matters is that our provided APIs behave as expected
from the perspective of packages which depend on Compat. The Compat
function calls in the test suite are just written in the same form as a
package developer would use them.

**Comment by minad** [comment]
On 3/19/23 11:16, Philip wrote:
>     What is the actual issue you want to solve?
> 
> The primary issue of this report is that I think prefixing our tests
> with |compat-| would be good. The secondary issue I brought up was that
> if we apparently aren't testing if the compatibility versions and the
> actual versions of all functions behave the same, we cannot make sure
> that the behavior of a compatibility function has changed due to the
> specific implementation (e.g. if it makes use of functions that changed
> their behavior). 

Why would it be good to prefix the tests with `compat-`? I am not fond
of pointless changes and I don't see a strong reason to add these prefixes.

You are right that we cannot cover everything, but that's also not
necessary. We can be reasonably sure, that nothing bad is going to
happen thanks to multiple factors:

- We observe new Emacs additions and changes by inspecting the change
log or commit log. Hopefully we can also improve package-lint to
understand Compat and to detect changes in function arguments. By
inspecting these diffs we can learn about potential issues.

- We run the test suite on all supported Emacs versions, including the
nightly snapshot and master. Our test coverage is quite good, since we
test basic cases and edge cases. It is not likely that suddenly
something is going to fail.

- We require full test coverage on the function level. Every definition
added to Compat has tests.

- Compat is widely rolled out. If something bad is going to happen we
will notice early and can act early. It is of course not great if
breakage happens, but Emacs itself is also causing breakage from time to
time. The standards applied here are reasonable, or are even higher than
the standards of Emacs itself, since we require tests for every single API.

> I guess one can say this is not that important, if the
> functions are not used from a certain version on? The exception here
> would be functions that should appear conditionally depending on how
> Emacs is configured (e.g. the JSON parsing functions). I also think that
> this it is a good idea to test more, because we might be able to learn
> about changes that would have otherwise been unnoticed.

See below regarding the JSON functions. I think the test coverage we
have right now is sufficient. If you find concrete problems, we can
address them. It seems to me that you want to write an additional test
suite in the style of the old test suite you had? Let me assure you that
this is not necessary.

>     If we observe bugs we can add test cases to prevent regressions.
> 
> IIUC these aren't caught by the test-suite, but would have to be
> manually observed?

Yes, but it seems your expectations go beyond what we can reasonably
provide. Of course one could try to write a fuzzer which compares the
behavior of builtin functions versus the Compat versions. But it is not
likely that this will catch any more bugs since as I argued, we copy
most definitions verbatim and provide a reasonable set of test cases
which should give sufficient coverage. It is not that likely that bugs
fall through this net.

>     if a function is provided conditionally (and must be called via
>     compat-call),
> 
> OK, I didn't know that conditional provided functions have to be called
> with compat-call... But does that really make sense? My understanding
> was that compat-call was to be used for functions that changed their
> signature between versions.

Ah I see. There was some misunderstanding. We don't have conditionally
provided functions right now, so we don't have to solve this right now.
In the past we provided the JSON functions conditionally. I tried to add
the JSON functions back to Compat, but came to the conclusion that it is
not a good idea, since our work can then not be used by :core packages
(python, jsonrpc, ...). We should instead add the compatibility
functions first to Emacs itself and then we can also add them to Compat.
See
https://github.com/emacs-compat/compat/commit/41460f01f0a808c9e8855f41417ded8cf804f442.
In principle the code from this commit be taken and put into Emacs if we
find an appropriate place for it.

**Comment by minad** [comment]
On 3/19/23 12:10, Philip wrote:
>     Why would it be good to prefix the tests with |compat-|? I am not
>     fond of pointless changes and I don't see a strong reason to add
>     these prefixes.
> 
> As mentioned above, it allows me to select only compat- test cases when
> calling ERT. That way I don't have to delete all the test cases I might
> have loaded in a given session.

Okay, fair enough. I've added prefixes.

>     Yes, but it seems your expectations go beyond what we can reasonably
>     provide.
> 
> What I was thinking about, was not so much to just test Compat, but also
> attempt and trigger as many edge-cases in Emacs as possible. This has
> the indirect advantage of noticing more subtle issues that might not
> immediately cause issues but would help us notice potential problems
> earlier.

I've also used Compat to find bugs in Emacs before. I am not sure which
route to take for this, but this sounds like a separate project of
Compat. Something like an Emacs fuzzer, which could rely on the Compat
test suite and the Emacs test suite.

>     But it is not likely that this will catch any more bugs since as I
>     argued, we copy most definitions verbatim and provide a reasonable
>     set of test cases which should give sufficient coverage. It is not
>     that likely that bugs fall through this net.
> 
> I get the point about the functions that were copied manually (but am
> not sure what happens in the upstream implementation will change at some
> point). Another concern for me are functions that cannot be copied,
> because they were written in C. I am hesitant to be satisfied with any
> claim like "It is not that likely that bugs fall through this net",
> because my intuition is that the bugs that will fall through will be
> worse still.

Sure, bugs can fall through, but we do our best to avoid it. A possible
solution could be to write more static analysis tools (see ELSA), add
more tests to Emacs itself, add more tests to Compat. Bugs will also
fall through in Emacs - it is not that this problem is unique to Compat.

>     I tried to add the JSON functions back to Compat, but came to the
>     conclusion that it is not a good idea, since our work can then not
>     be used by :core packages (python, jsonrpc, ...).
> 
> Oh, why is that?

The :core packages are part of Emacs, but Compat is not available there,
since these packages would require Compat with the NOERROR argument. See
how it is done in ERC for example. This means such conditional
compatibility functions will never be available :(

See also the reasoning in the commit
https://github.com/emacs-compat/compat/commit/41460f01f0a808c9e8855f41417ded8cf804f442

>     In principle the code from this commit be taken and put into Emacs
>     if we find an appropriate place for it.
> 
> True, there was a discussion on the mailing list
> <https://lists.sr.ht/~pkal/compat-devel/%3C87y21ydc9k.fsf%40gmail.com%3E> on the topic.

Very good. Let's pursue this. It would be nice if the json-* functions
were always available, in particular for :core packages. Note that both
python.el and jsonrpc.el already contain fallback compatibility
implementations. It would be great to get rid of those.

Generally we should aim to make Compat equally useful for both :core and
external packages.
