### ISSUE TITLE
New autoloads in text-property-search.el

### ISSUE THREAD

**Issue by astoff** [emacs-compat/compat#22]
Is compat in the business of adding autoloads when the same is done upstream? I noticed text-property-search.el has gained several of them in Emacs 29.

**Comment by minad** [comment]
> I noticed text-property-search.el has gained several of them in Emacs 29.

Where did you find these autoloads? There are none defined in https://github.com/emacs-mirror/emacs/blob/emacs-29/lisp/emacs-lisp/text-property-search.el. 

I only found that autoloads are added in outline.el among others. Such "scattered" autoloads are questionable and not recommended, since they unexpectedly affect users of outline.el. Scattered autoloads are out of scope of Compat also since outline.el does not belong to the set of libraries which are ported back by Compat.

> Is compat in the business of adding autoloads when the same is done upstream?

Generally speaking we could add `(autoload 'some-autoloaded-function ...)` declarations in compat-version.el, such that one gets access to them when Compat is required. Currently we don't provide any such autoloads, but if autoloads are added to Compat-supported libraries we should definitely try this out.

**Comment by astoff** [comment]
I'm confused by that too, but `C-h f` tells me:
```
text-property-search-forward is an autoloaded interactive
byte-compiled Lisp function in ‘text-property-search.el’.
```

**Comment by minad** [comment]
This probably happens if you have outline.el loaded? As I mentioned, it is considered a bad pattern to declare autoloads in unrelated packages.

**Comment by astoff** [comment]
Ah, I misunderstood you comment about outline on the first reading.
