### ISSUE TITLE
string-pixel-width hangs at least emacs 28.2 when used with doom modeline

### ISSUE THREAD

**Issue by felipebalbi** [emacs-compat/compat#8]
Hi,

There's a long [discussion](https://github.com/seagle0128/doom-modeline/issues/601) on the doom modeline repository regarding a regression after an upgrade. It turns out that the hang was introduced by doom modeline's change to using `string-pixel-width`. Removing the single usage of that function from doom modeline makes everything work okay, so it appears that the bug lies in `string-pixel-width`.

Happy to test suggestions :-)

**Comment by minad** [comment]
Thanks for debugging and figuring out this issue!

**Comment by felipebalbi** [comment]
Glad I was able to help :-)

**Comment by sdevlin** [comment]
Hi, see also https://lists.gnu.org/archive/html/bug-gnu-emacs/2023-01/msg00386.html.

**Comment by minad** [comment]
@sdevlin Thanks for debugging this. You may close the bug on the bug tracker. The issue has been fixed since then via the release of Compat 29.1.1.0. In the future, if you observe Compat-related issues, please report these issues directly on the Compat issue tracker or via mail to the me, since I may miss them on the Emacs bug tracker, in particular since the subject didn't contain "Compat".
